before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - npm install mysql2 mysql pg
  - npm install sequelize@$(echo $SEQUELIZE)

script:
  - travis_retry node_modules/.bin/gulp

env:
  - DIALECT=postgres SEQUELIZE=3.30.2
  - DIALECT=mysql SEQUELIZE=4.0.0-2

language: node_js

node_js:
  - "4.0"

sudo: false

addons:
  postgresql: "9.4"

cache:
  directories:
    - node_modules
